# Generated by Django 5.1.2 on 2024-10-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
