# Generated by Django 5.1.2 on 2024-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todoitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
