# Generated by Django 5.1.2 on 2024-10-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_todoitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
