# Generated by Django 5.1.2 on 2024-10-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_todoitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='userid',
            field=models.IntegerField(default=-1, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
        ),
    ]
