# Generated by Django 5.1.2 on 2024-10-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_todoitem_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='userid',
        ),
    ]
